services:
  - type: web
    name: hotel-management-backend
    env: docker
    plan: free
    region: singapore
    envVars:
      - key: PORT
        value: 8080
      - key: FRONTEND_URL
        value: https://hotel-management-frontend-mjbr.onrender.com
      - key: SPRING_PROFILES_ACTIVE
        value: prod
